spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_wechatyiyu?characterEncoding=utf8&allowMultiQueries=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        enabled: true
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 8
    database: 8

logging:
  level:
    com.example.wechat.dao: DEBUG
    web: debug
jwt:
  # 为JWT基础信息加密和解密的密钥，长度需要大于等于43
  # 在实际生产中通常不直接写在配置文件里面。而是通过应用的启动参数传递，并且需要定期修改
  secret: oQZSeguYloAPAmKwvKqqnifiQatxMEPNOvtwPsCLasd
  # JWT令牌的有效时间，单位秒，默认2周
  expiration: 1209600
  header: Authorization
mybatis-plus:
  mapper-locations: classpath*:**/*Dao.xml
